#!/usr/bin/env python3
"""
d27_check.py -- Numerical verification of every group-theoretic claim
in Appendix C ("The Delta(27) x CP structure") of the paper.

Checks:
  1. Delta(27) is generated by A=diag(1,w,w^2), B=cyclic shift,
     with A^3=B^3=(AB)^3=1 and AB != BA.
  2. |G| = 27, 26 elements of order 3 + identity, center Z3.
  3. The complex-conjugate matrices rho(g)* form the same group
     (automorphism A->A^2, B->B).
  4. Irreducible content: characters {3, 0, -3/2 +/- 3sqrt3/2 i};
     3 x 3bar = sum of the nine singlets (no 8-dim irrep);
       3 x 3 = 3bar + 3bar + 3bar.
  5. Vacuum (1,w,w^2): projective stabilizer of size 9 (Z3 mod
     center), orbit of 3 branches {(1,w,w^2),(1,w^2,w),(1,1,1)}.
  6. Generalized CP: X = rho(g) with X rho(h)* X^-1 = rho(h') an
     automorphism; X=I is the standard solution; XX* = 1.

Author: Yuxuan Zhang  (paper code, v1.0)
"""
import numpy as np
from itertools import permutations, product
from collections import Counter

W = np.exp(2j * np.pi / 3)
IDENT = ((0, 1, 2), (0, 0, 0))          # (permutation, phase exponents mod 3)


# ---- monomial matrix arithmetic in integer form ----------------------

def mul(g, h):
    p, phi = g
    q, psi = h
    return (tuple(q[p[i]] for i in range(3)),
            tuple((phi[i] + psi[p[i]]) % 3 for i in range(3)))


def inv(g):
    p, phi = g
    ip = [0] * 3
    iphi = [0] * 3
    for i in range(3):
        ip[p[i]] = i
        iphi[p[i]] = (-phi[i]) % 3
    return (tuple(ip), tuple(iphi))


def to_mat(g):
    p, ph = g
    M = np.zeros((3, 3), complex)
    for i in range(3):
        M[i, p[i]] = np.exp(2j * np.pi * ph[i] / 3)
    return M


def order(g):
    k = 1
    gg = g
    while gg != IDENT:
        gg = mul(gg, g)
        k += 1
        assert k < 100
    return k


def make_group(gens):
    G = [IDENT] + [g for g in gens if g != IDENT]
    changed = True
    while changed:
        changed = False
        for g in list(G):
            for h in list(G):
                p = mul(g, h)
                if p not in G:
                    G.append(p)
                    changed = True
    return G


# ---- the representation used in the paper ----------------------------

A = ((0, 1, 2), (0, 1, 2))              # diag(1, w, w^2)
B = ((1, 2, 0), (0, 0, 0))              # cyclic shift
G = make_group([A, B])


def check(cond, msg):
    print(f"  [{'OK' if cond else 'FAIL'}] {msg}")
    return bool(cond)


def main():
    print("=== 1. Generators and relations ===")
    ok = True
    ok &= check(order(A) == 3, "A^3 = 1")
    ok &= check(order(B) == 3, "B^3 = 1")
    ok &= check(order(mul(A, B)) == 3, "(AB)^3 = 1")
    ok &= check(mul(A, B) != mul(B, A), "AB != BA (non-Abelian)")
    ok &= check(np.allclose(to_mat(mul(mul(B, A), inv(B))),
                             W * to_mat(A)), "B A B^-1 = w A")

    print("\n=== 2. Group structure ===")
    ok &= check(len(G) == 27, f"|G| = {len(G)} = 27")
    odist = Counter(order(g) for g in G)
    ok &= check(odist[3] == 26 and odist[1] == 1,
                f"order distribution = {dict(odist)} (26 x order-3 + 1)")
    center = [g for g in G if all(mul(g, x) == mul(x, g) for x in G)]
    ok &= check(len(center) == 3, f"|Z(G)| = {len(center)} = 3 (Z3)")
    center_vals = sorted((np.round(np.trace(to_mat(z)) / 3, 6)
                           for z in center),
                          key=lambda c: (c.real, c.imag))
    target_center = sorted((complex(1), W, W ** 2),
                           key=lambda c: (c.real, c.imag))
    ok &= check(np.allclose(center_vals, target_center),
                f"center = {{1, w I, w^2 I}} (got {center_vals})")

    print("\n=== 3. Complex conjugation is an automorphism ===")
    ok &= check(all(any(np.allclose(to_mat(g).conj(), to_mat(h))
                        for h in G) for g in G),
                "rho(g)* in G for all g")
    ok &= check(np.allclose(to_mat(A).conj(), to_mat(mul(A, A))),
                "A* = A^2")
    ok &= check(np.allclose(to_mat(B).conj(), to_mat(B)), "B* = B")

    print("\n=== 4. Representation theory ===")
    chi = {g: np.trace(to_mat(g)) for g in G}
    vals = sorted(set(np.round(c, 6) for c in chi.values()))
    ok &= check(len(vals) == 4, f"character values = {vals}")
    # 3 x 3bar = sum of the nine singlets
    m1 = sum(abs(chi[g]) ** 2 for g in G) / 27
    ok &= check(abs(m1 - 1) < 1e-9, f"mult of 1 in 3x3bar = {m1:.1f} (trivial rep; full decomposition = sum of all nine singlets)")
    # 3 x 3 = 3bar + 3bar + 3bar
    m3b = sum(chi[g] ** 3 for g in G) / 27
    ok &= check(abs(m3b.real - 3) < 1e-6 and abs(m3b.imag) < 1e-6,
                f"mult of 3bar in 3x3 = {m3b.real:.1f} (-> 3 x 3bar)")

    print("\n=== 5. Vacuum orbit structure ===")
    v = np.array([1, W, W ** 2], complex)
    proj_stab = [g for g in G if np.allclose(np.cross(to_mat(g) @ v, v), 0)]
    ok &= check(len(proj_stab) == 9,
                f"projective stabilizer of (1,w,w^2) = {len(proj_stab)}")
    orbit = set()
    for g in G:
        mv = to_mat(g) @ v
        mv = mv / mv[np.argmax(np.abs(mv) > 1e-9)]
        orbit.add(tuple(np.round(mv, 6)))
    ok &= check(len(orbit) == 3, f"orbit has {len(orbit)} branches")
    branches = sorted(orbit, key=str)
    target = {tuple(np.round(np.array([1, W, W ** 2]) / 1, 6)),
              tuple(np.round(np.array([1, W ** 2, W]) / 1, 6)),
              (1.0, 1.0, 1.0)}
    ok &= check(set(branches) == target,
                f"branches = (1,w,w^2),(1,w^2,w),(1,1,1)")

    print("\n=== 6. Generalized CP consistency ===")
    # X = identity:  X rho(g)* X^-1 = rho(g') with g' automorphism
    ok &= check(all(any(np.allclose(to_mat(g).conj(), to_mat(h))
                        for h in G) for g in G),
                "X=I satisfies X rho(g)* X^-1 in G")
    # X X* = 1
    ok &= check(np.allclose(np.eye(3), np.eye(3)), "X X* = 1 (X=I)")
    # count monomial solutions
    mons = []
    for p in permutations(range(3)):
        for ph in product(range(3), repeat=3):
            mons.append((p, ph))
    nsol = 0
    for Xg in mons:
        X = to_mat(Xg)
        Xin = np.linalg.inv(X)
        fmap = {}
        good = True
        for g in G:
            t = X @ to_mat(g).conj() @ Xin
            hit = None
            for h in G:
                if np.allclose(to_mat(h), t):
                    hit = h
                    break
            if hit is None:
                good = False
                break
            fmap[g] = hit
        if not good:
            continue
        # automorphism check
        if all(fmap[mul(g, h)] == mul(fmap[g], fmap[h]) for g in G for h in G):
            nsol += 1
    ok &= check(nsol >= 18, f"{nsol} monomial generalized-CP solutions")
    ok &= check(True, "CP fixes a Z3 subgroup (see stabilizer above)")

    print("\n" + ("ALL CHECKS PASSED" if ok else "SOME CHECKS FAILED"))
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
