#!/usr/bin/env python3
"""
variational.py -- Variational method: can a flavon scalar potential
produce the structural ratios {1/2, 9/11, 45/22, 1/3}?

Key observation from perturb_analysis: d2-d1 and d2+d1 both have
clean 1/11 fractions:
    (d2-d1)/a12 ~ 34/11,  (d2+d1)/a12 ~ 23/11,  d2/d3 ~ 9/11
The common denominator 11 suggests a variational origin: ratios of
VEVs from minimizing a potential with a discrete symmetry.

Model: three real+complex flavon VEVs (v13, v23, v33) with a Z3-symmetric
potential V = sum(-mu^2 |v|^2 + lam |v|^4) + cross terms.  We ask:
which potential coefficients make the VEV ratios equal the observed
parameter ratios, and whether those coefficients are 'natural'
(simple, O(1)).

Texture -> VEV map (from uv_completion):
    a12 = c12                (direct Weinberg, no flavon)
    a13 = c13 * eps13        (eps13 = <phi13>/Lambda)
    a23 = c23 * eta23        (eta23 = <phi23>/Lambda)
    d3  = c33 * eta33        (eta33 = <chi33>/Lambda)
    d1, d2 = c11, c22        (direct)
Assume O(1) Wilson coefficients ~ 1: then
    eta33 = d3 ~ 1.41,  eta23 = a23 ~ 0.91,  eps13 = a13 ~ 0.149
"""
import numpy as np
from scipy.optimize import minimize

m0, d1, d2, d3, a12, a23 = 0.02242954, -0.22256984, 1.15386934, 1.40954774, 0.44558787, 0.91190663

print("=== observed VEV ratios (Wilson ~ 1) ===")
r23 = a23 / d3          # eta23/eta33
r13 = (a12 / 3) / d3    # eps13/eta33
print(f"eta23/eta33 = {r23:.6f}  (~ 0.647?)")
print(f"eps13/eta33 = {r13:.6f}  (~ 0.105?)")
print(f"d3  = {d3:.4f}  (scale)")
print(f"d2  = {d2:.4f}  (direct, no VEV)")
print(f"d1  = {d1:.4f}  (direct, no VEV, NEGATIVE)")

print("\n=== problem: d1 < 0 with direct Weinberg ===")
print("direct Weinberg (L1H)(L1H) coefficient c11 must be positive")
print("(from |c11|^2 in potential).  Observed d1 = -0.223 < 0.")
print("=> d1 NEGATIVE requires either a sign from dynamics, or")
print("   a non-trivial mechanism.  d1 = -a12/2 = -c12/2 is")
print("   surprisingly clean.  Variational origin?")
print()
print("=== variational toy: two-flavon mixing ===")
print("Consider d1 and a12 generated by a 2x2 sector with potential")
print("  V = -m1^2|phi1|^2 - m2^2|phi2|^2 + lam1|phi1|^4 + lam2|phi2|^4")
print("     + 2 lam12 |phi1|^2 |phi2|^2")
print("Minimizing: <phi_i>^2 = (m_i^2 - lam12 <phi_j>^2)/lam_i")
print("For equal couplings (lam1=lam2=lam12=lam):")
print("  <phi1>^2 = (2 m1^2 - m2^2)/(3 lam),  <phi2>^2 = (2 m2^2 - m1^2)/(3 lam)")
print("  ratio^2 = (2m1^2-m2^2)/(2m2^2-m1^2)")
print("If m2^2 = 2 m1^2 (hierarchical masses): ratio^2 = 0 -> degenerate")
print("If m1=m2: ratio = 1 (degenerate)")
print("=> quadratic terms alone give ratio 1 or 0; need cubic terms")
print("   (which Z3 symmetry provides via phi^3 + h.c.!)")

print("\n=== with Z3 cubic terms: V3 = -k(phi^3 + phi*^3) ===")
print("phi = rho e^{i theta}: V3 = -2k rho^3 cos(3 theta)")
print("minimized at theta = 0 (or 2pi/3, 4pi/3): the Z3 branches!")
print("radial: d/d rho [-m^2 rho^2 + lam rho^4 - 2k rho^3] = 0")
print("  -2m^2 rho + 4 lam rho^3 - 6k rho^2 = 0")
print("  rho(2 lam rho^2 - 3k rho - m^2) = 0")
print("  rho* = [3k + sqrt(9k^2 + 8 lam m^2)] / (4 lam)")
print("=> VEV determined by (k, lam, m^2): the RATIO of two VEVs")
print("   is fixed by the ratio of (k_i, lam_i, m_i^2).")

print("\n=== numerical scan: can ratios 0.91/1.41, 0.149/1.41 arise? ===")
# Solve rho*(k,lam,m) = [3k + sqrt(9k^2+8 lam m^2)]/(4 lam)
def rho_star(k, lam, m2):
    return (3 * k + np.sqrt(9 * k ** 2 + 8 * lam * m2)) / (4 * lam)

# want: eta23/eta33 = 0.647, eps13/eta33 = 0.105, eta33 = 1.41
a13 = a12 / 3.0
targets = {"eta33": d3, "eta23": a23, "eps13": a13}
print(f"targets: eta33={d3:.3f}, eta23={a23:.3f}, eps13={a13:.3f}")
print(f"ratios: eta23/eta33={r23:.4f}, eps13/eta33={r13:.4f}")

# scan for simple (k,lam,m2) giving these
found = []
for k in np.linspace(0.1, 2.0, 40):
    for lam in np.linspace(0.1, 2.0, 40):
        for m2 in np.linspace(0.1, 2.0, 40):
            v = rho_star(k, lam, m2)
            if 1.3 < v < 1.5:
                # ratio to a second VEV with scaled params
                for s in np.linspace(0.1, 1.5, 30):
                    v2 = rho_star(s * k, s * lam, s * m2)
                    if v2 > 0 and abs(v2 / v - r23) < 0.02:
                        found.append((k, lam, m2, s, v, v2, "eta23/eta33"))
print(f"\nfound {len(found)} configs for eta23/eta33 = {r23:.3f}")
for f in found[:5]:
    k, lam, m2, s, v, v2, tag = f
    print(f"  k={k:.2f} lam={lam:.2f} m2={m2:.2f} s={s:.2f} -> "
          f"v={v:.3f} v2={v2:.3f} ratio={v2/v:.3f}  [{tag}]")

# direct approach: what VEV ratio gives d2/d3=9/11 directly?
print("\n=== direct: d2/d3 = 9/11 from VEV ratio ===")
print("d2 = c22 (direct), d3 = c33*eta33")
print("d2/d3 = c22/(c33 eta33) = 9/11")
print("with c22=c33=1: eta33 = 11/9 = 1.222, but observed d3 = 1.41")
print("with c22=1, c33=2/3: eta33 = (11/9)(3/2) = 11/6 = 1.833")
print("with c22=2/3, c33=1: eta33 = (11/9)(2/3) = 22/27 = 0.815")
print("=> no natural O(1) assignment gives eta33 = 1.41 exactly")
print("   (the 9/11 lives in d2/d3, not in a VEV ratio directly)")
